### ISSUE TITLE
Store points in a database

### ISSUE THREAD

**Issue by lucasmontano** [lucasmontano/twitch#12]
https://devcenter.heroku.com/articles/mongolab or https://devcenter.heroku.com/articles/ormongo

**Comment by fernandovfilho** [comment]
You can use Heroku Postgres as database, it's free until 10k rows, to activate this access "Resources" find the add-on "Heroku Postgres".

**Comment by HenriqueDerosa** [comment]
What else would be stored in this database ?

**Comment by lucasmontano** [comment]
@HenriqueDerosa for now just the username of the participants and their points :)

**Comment by HenriqueDerosa** [comment]
@lucasmontano I asked because maybe we could use a mongodb instead of a relational database. I don't know. But it depends. Maybe you're gonna do some relations in an `unknown future` 👀

**Comment by OvictorVieira** [comment]
As it is a simple application initially that will record only the participant's name and points, wouldn't it be legal to use a mongo in this case?

The **mLab on heroku has 496mb of memory for free use**, what do you think?

**mLab Heroku:** https://elements.heroku.com/addons/mongolab

Using Postgres, I see that we can be limited to the **10k of records that it provides**, allowing us to create only 10k of users in the table and so we would be somewhat limited. I had this problem when I went to create some records with a routine that I created and the government API had 40k of data to insert, I was limited in this question of the bank.

**Comment by lucasmontano** [comment]
That's a good point @OvictorVieira "496 MB" will allow us to store more than 10k participants/points

**Comment by lucasmontano** [comment]
@HenriqueDerosa I think we can move away from a relational database indeed. Most ideas I have in my mind for the future are related to aggregated data. Mongolab on Heroku seems like a good start.

**Comment by lucasmontano** [comment]
I did a quick research about [ObjectRocket](https://devcenter.heroku.com/articles/ormongo) vs [mLab](https://devcenter.heroku.com/articles/mongolab): IMO mLab seems more reliable as it's part of MongoDB (acquired in 2018). Do you have a diff opinion?

**Comment by OvictorVieira** [comment]
@luacsmontano Analyzing [ObjectRocket] (https://devcenter.heroku.com/articles/ormongo) and seeing his plans, apparently he doesn't have an initial free plan, that is, to use the service you need to pay a [plan $ 46 / month] (https://elements.heroku.com/addons/ormongo). In mLab, you have an [initial free plan](https://elements.heroku.com/addons/mongolab).

**Comment by lucasmontano** [comment]
@OvictorVieira but even on mLab, I have to add my credit card. I'm not willing to do this right now, so I think I'll go back to the postgress approach (It's free and we don't need to add credit card) =(

**Comment by OvictorVieira** [comment]
To use some addons in heroku it is necessary to add the same credit card. :~/

We have another option, what do you think of [Mongodb Atlas](https://www.mongodb.com/cloud/atlas)? It is a service external to heroku but it is free, it has an initial [plan with 512mb of storage](https://www.mongodb.com/blog/post/new-to-mongodb-atlas--get-started-with-free-database-tier-on-microsoft-azure) and it is a service maintained by Mongodb. @diego3g used it in a video on his channel once.

**Comment by HenriqueDerosa** [comment]
Once I did my account in mLab. I didn't use that much, but I was checking here, and I didn't have to add my credit card. 🤔  But we could check Mongodb Atlas as @OvictorVieira said as well.
