### ISSUE TITLE
Write tests for database operations and its functions

### ISSUE THREAD

**Issue by powilliam** [lucasmontano/twitch#21]
To avoid the necessity of have [mongod](https://www.mongodb.com/download-center/community) locally installed or use its cloud services i pretend to use an implementation of MongoDB for [memory storage](https://github.com/nodkz/mongodb-memory-server).

**Comment by EduardoAraujoB** [comment]
Create a mock for the database is a great option to test it

**Comment by HenriqueDerosa** [comment]
Is it worth to use a testing database version to do real tests for database operations?
Or is it enough to test with mock. If it is database operations, we might need a database, right? 🤷🏻‍♂️

**Comment by EduardoAraujoB** [comment]
Maybe define a SQLite database for tests is a great option, but we will have problems beacuse the test for database operations will be assyncronous

**Comment by powilliam** [comment]
That's why i'm using [MongoDB Memory Server](https://github.com/nodkz/mongodb-memory-server). It uses the latest ```mongod``` binary located on```node_modules/.cache/mongodb-binaries``` to setup a MongoDB memory database. [jest-mongodb](https://github.com/shelfio/jest-mongodb) uses it under the hood. By this way we don't have to setup a real database.

**Comment by HenriqueDerosa** [comment]
To test, we could just create a local database with Mongo [Article: setup a local MongoDB Connection](https://zellwk.com/blog/local-mongodb/)

**Comment by powilliam** [comment]
Closing due to#26
