### ISSUE TITLE
Replace eslint with tslint

### ISSUE THREAD

**Issue by luancaike** [lucasmontano/twitch#23]
The substitution would be useful because eslint is only prepared for cases in javascript vanilla while tslint is not only ready to deal with it but also handles typing better.
Ex: Interfaces, abstraction, autocomplete ...

**Comment by jasondavindev** [comment]
TSLint is deprecated

https://github.com/palantir/tslint/issues/4534

**Comment by EduardoAraujoB** [comment]
Currently, Eslint have a great integration with Typescript, so Tslint is not necessary anymore and how was citted above, is deprecated
