### ISSUE TITLE
Fix application options on Readme

### ISSUE THREAD

**Issue by barbozafernando** [lucasmontano/twitch#7]
As we could see on livestream, I suggest changing the APP_PORT to PORT only.

**Application Options:**
```
APP_PORT: Set the port of the application
```

**Comment by EduardoAraujoB** [comment]
Hey this issue was already solved [here](https://github.com/lucasmontano/twitch/commit/f492a1458f7ebd1131a8d61ec0eb11bb795f9851)

**Comment by barbozafernando** [comment]
Hm, I dont think so. In that commit, he just changed the name on .env and server.ts file. Not in readme.

**Comment by EduardoAraujoB** [comment]
Thanks, we need to fix the readme, alright

**Comment by EduardoAraujoB** [comment]
Can you open a PR fixing it?

**Comment by barbozafernando** [comment]
Yes, I'll do it.
